name: "Publish to NPM"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install
        working-directory: ./subfolder

      - name: Build Package
        run: npm run build
        working-directory: ./subfolder

      - name: Publish to npm
        run: npm publish --access public
        working-directory: ./subfolder
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
